LOCAL_PATH:= $(call my-dir)

# build device static library
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	reboot.c

LOCAL_MODULE:= libreboot

ifeq ($(BOARD_USES_BOOTMENU),true)
	LOCAL_SRC_FILES := ../../../external/bootmenu/libreboot/reboot.c
endif

ifneq ($(TARGET_RECOVERY_PRE_COMMAND),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND='$(TARGET_RECOVERY_PRE_COMMAND)'
endif

ifneq ($(TARGET_REBOOT_REASON_DEFAULT),)
	LOCAL_CFLAGS += -DREBOOT_REASON_DEFAULT='$(TARGET_REBOOT_REASON_DEFAULT)'
endif

ifneq ($(TARGET_RECOVERY_PRE_COMMAND_CLEAR_REASON),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND_CLEAR_REASON
endif

include $(BUILD_STATIC_LIBRARY)


# build device static library
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	reboot.c

LOCAL_MODULE:= librebootrecovery

ifneq ($(TARGET_RECOVERY_PRE_COMMAND),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND='$(TARGET_RECOVERY_PRE_COMMAND)'
endif

ifneq ($(TARGET_RECOVERY_PRE_COMMAND_CLEAR_REASON),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND_CLEAR_REASON
endif

LOCAL_CFLAGS += -DRECOVERY_SHELL
LOCAL_STATIC_LIBRARIES += libcrecovery

include $(BUILD_STATIC_LIBRARY)
